### ISSUE TITLE
pcmanfm missing menu icons

### ISSUE THREAD

**Issue by skarbat** [raspberrypi-ui/libfm#1]
On a raspbian-based distro, `pcmanfm` seems to have lost the top menu icons since moving to Debian Stretch. Manually installing:

 * http://ftp.us.debian.org/debian/pool/main/libf/libfm/libfm4_1.3.0.2-1_armhf.deb

Seems to fix this problem, but breaks a bunch of dependencies related to LXDE. Any ideas on wether this repository will be put up-to-date and a new `libfm4` package pushed to Raspbian repositories?

**Comment by spl237** [comment]
Menu icons have been deliberately disabled in the theme, as they cause unnecessary clutter.

If you want to re-enable them, edit ~/.config/lxsession/LXDE-pi/desktop.conf and change the line iGtk/MenuImages=0 to iGtk/MenuImages=1
